[build]
  command = "npm run build"
  publish = "dist"
  functions = "src/functions"
  NODE_ENV = "10.15.3"

[dev]
  command = "npm run start"


[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "https://fjchen.net"
  to = "https://finleychen.dev"
  status = 301
  force = true
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}
